export interface respostasAvaliacao{
    questao_1: string
    questao_2: string
    questao_3: string
    questao_4: string
    questao_5: string
    questao_6: string
    questao_7: string
    questao_8: string
    questao_9: string
    questao_10: string
    questao_11: string
    questao_12: string
    questao_13: string
    questao_14: string
    questao_15: string
    questao_16: string
    questao_17?: string
    questao_18?: string
    questao_19?: string
    questao_20?: string
    atividade_complexa?: boolean
    metas_pontos_fortes?: string
    metas_pontos_fracos?: string
    metas_melhorias?: string
    inibidores_falta_integracao?: boolean
    inibidores_falta_funcao?: boolean
    inibidores_problemas_particulares?: boolean
    inibidores_dificuldades_chefia?: boolean
    inibidores_desinteresse_servidor?: boolean
    inibidores_outros?: string
    conclusao_apto?: boolean
    observacoes?: string
    sugestoes?: string
    uso_alcool_drogas?: boolean
}